import { MetricDefinition } from '../types/kpi';

export const SYSTEM_METRIC_LIBRARY: MetricDefinition[] = [
  {
    id: 'm-ontime-rate',
    key: 'ON_TIME_COMPLETION_RATE',
    name: 'On-time Completion Rate',
    description: 'Percentage of completed story points that were resolved on or before the committed deadline.',
    category: 'DELIVERY',
    unit: '%',
    formulaSummary: '(On-time Story Points / Total Completed Story Points) * 100%',
    requiredFields: ['Story Points', 'Deadline Date', 'Resolved Date', 'Status'],
    supportedIssueTypes: ['Story', 'Task', 'Improvement'],
    dataQualityRequirements: 'Requires non-null Deadline and non-null Story Points. Missing deadlines flag Medium confidence.',
    usageCount: 14,
  },
  {
    id: 'm-task-completion-rate',
    key: 'TASK_COMPLETION_RATE',
    name: 'Sprint / Task Completion Rate',
    description: 'Ratio of total completed story points versus initial committed story points in the period sprints.',
    category: 'DELIVERY',
    unit: '%',
    formulaSummary: '(Completed Story Points / Committed Story Points) * 100%',
    requiredFields: ['Story Points', 'Sprint', 'Status'],
    supportedIssueTypes: ['Story', 'Task', 'Improvement', 'Bug'],
    dataQualityRequirements: 'Requires Story Points on all committed sprint tasks.',
    usageCount: 18,
  },
  {
    id: 'm-completed-sp',
    key: 'COMPLETED_STORY_POINTS',
    name: 'Completed Story Points Velocity',
    description: 'Total completed Story Points delivered within the evaluation period.',
    category: 'PRODUCTIVITY',
    unit: 'SP',
    formulaSummary: 'Sum of Story Points for all Resolved/Done tickets in period',
    requiredFields: ['Story Points', 'Status', 'Resolved Date'],
    supportedIssueTypes: ['Story', 'Task', 'Improvement', 'Bug'],
    dataQualityRequirements: 'Tickets with missing Story Points default to team median estimate with low confidence tag.',
    usageCount: 9,
  },
  {
    id: 'm-carryover-rate',
    key: 'CARRY_OVER_RATE',
    name: 'Task Carry-over Rate',
    description: 'Percentage of committed tasks that could not be finished within the active sprint and carried over.',
    category: 'DELIVERY',
    unit: '%',
    formulaSummary: '(Carry-over Ticket Count / Total Committed Ticket Count) * 100%',
    requiredFields: ['Sprint', 'Carry-over Flag', 'Created Date'],
    supportedIssueTypes: ['Story', 'Task'],
    dataQualityRequirements: 'Sprint close event snapshots required.',
    usageCount: 12,
  },
  {
    id: 'm-bug-rate',
    key: 'BUG_RATE',
    name: 'Defect & Bug Ratio',
    description: 'Proportion of bug/defect tickets assigned vs total delivered feature tasks.',
    category: 'QUALITY',
    unit: '%',
    formulaSummary: '(Bug Ticket Count / (Delivered Stories + Tasks)) * 100%',
    requiredFields: ['Issue Type', 'Status', 'Resolved Date'],
    supportedIssueTypes: ['Bug', 'Story', 'Task'],
    dataQualityRequirements: 'Accurate bug labeling on Jira issue creation.',
    usageCount: 15,
  },
  {
    id: 'm-reopen-rate',
    key: 'REOPEN_RATE',
    name: 'QA Reopen Rate',
    description: 'Percentage of resolved tasks that failed QA verification and were reopened.',
    category: 'QUALITY',
    unit: '%',
    formulaSummary: '(Reopened Ticket Count / Total Closed Tickets) * 100%',
    requiredFields: ['Reopen Count', 'Status'],
    supportedIssueTypes: ['Story', 'Task', 'Bug'],
    dataQualityRequirements: 'Jira workflow must track transitions through In QA / Reopened.',
    usageCount: 11,
  },
  {
    id: 'm-incident-count',
    key: 'INCIDENT_COUNT',
    name: 'P1 / P2 Production Incident Count',
    description: 'Number of high-severity production incidents or outages attributed to member service changes.',
    category: 'INCIDENT',
    unit: 'COUNT',
    formulaSummary: 'Count of P1/P2 Incident tickets resolved in the period',
    requiredFields: ['Issue Type', 'Priority', 'Resolved Date'],
    supportedIssueTypes: ['Incident'],
    dataQualityRequirements: 'Post-mortem incident reports must link to Jira tickets.',
    usageCount: 16,
  },
  {
    id: 'm-mttr-hours',
    key: 'INCIDENT_MTTR_HOURS',
    name: 'Incident Resolution Speed (MTTR)',
    description: 'Average time taken from incident creation to production mitigation.',
    category: 'INCIDENT',
    unit: 'HOURS',
    formulaSummary: 'Average(Mitigation Time - Detected Time) in hours',
    requiredFields: ['Created Date', 'Resolved Date', 'Priority'],
    supportedIssueTypes: ['Incident', 'Support'],
    dataQualityRequirements: 'Exact timestamp tracking for incident lifecycle.',
    usageCount: 8,
  },
  {
    id: 'm-knowledge-sharing',
    key: 'KNOWLEDGE_SHARING',
    name: 'Technical Sharing & RFC Contributions',
    description: 'Number of technical workshops, internal tech talks, RFC proposals, or architecture docs delivered.',
    category: 'INNOVATION',
    unit: 'COUNT',
    formulaSummary: 'Count of Confluence RFCs or verified internal tech talk sessions',
    requiredFields: ['Manual Evidence / Confluence Link'],
    supportedIssueTypes: ['Support', 'Task'],
    dataQualityRequirements: 'Manual evidence submission with Leader verification.',
    usageCount: 13,
  },
  {
    id: 'm-custom-score',
    key: 'CUSTOM_METRIC',
    name: 'Custom Team Specific Metric',
    description: 'User-defined calculation formula or manual rubric scoring for specialized team criteria.',
    category: 'CUSTOM',
    unit: 'SCORE',
    formulaSummary: 'Configured by team manager in rule builder',
    requiredFields: ['Custom Inputs'],
    supportedIssueTypes: ['Story', 'Task', 'Bug', 'Incident', 'Support'],
    dataQualityRequirements: 'Configurable by team leader.',
    usageCount: 6,
  },
];
