import {
  Department,
  Team,
  Member,
  TeamMembership,
  KpiTemplate,
  EvaluationPeriod,
  RankScheme,
  JiraIssue,
  DataQualityIssue,
  AuditEvent,
  JiraConnectionConfig,
} from '../types/kpi';

export const SEED_DEPARTMENT: Department = {
  id: 'dept-backend',
  name: 'Backend Engineering Department',
  code: 'BED',
  headId: 'm-head-tuan',
  headName: 'Dr. Tuan Nguyen',
  description: 'Core backend platform, transactional microservices, payment gateways, and database infrastructure.',
};

export const SEED_TEAMS: Team[] = [
  {
    id: 'team-api',
    departmentId: 'dept-backend',
    name: 'API Core Platform',
    code: 'API',
    leaderId: 'm-minh-lead',
    leaderName: 'Nguyen Van Minh',
    description: 'High-throughput public API gateways, gRPC microservices, and identity infrastructure.',
    status: 'ACTIVE',
    activeTemplateId: 'tpl-api-v2',
    createdAt: '2025-01-10',
  },
  {
    id: 'team-payment',
    departmentId: 'dept-backend',
    name: 'Payment & Billing',
    code: 'PAY',
    leaderId: 'm-mai-lead',
    leaderName: 'Tran Thi Mai',
    description: 'Payment switch, checkout processing, reconciliation pipelines, and PCI-DSS compliance.',
    status: 'ACTIVE',
    activeTemplateId: 'tpl-pay-v1',
    createdAt: '2025-01-15',
  },
  {
    id: 'team-cms',
    departmentId: 'dept-backend',
    name: 'CMS & Content Services',
    code: 'CMS',
    leaderId: 'm-long-lead',
    leaderName: 'Le Hoang Long',
    description: 'Enterprise content graph, asset transformation pipelines, and GraphQL editorial APIs.',
    status: 'ACTIVE',
    activeTemplateId: 'tpl-cms-v1',
    createdAt: '2025-02-01',
  },
  {
    id: 'team-ads',
    departmentId: 'dept-backend',
    name: 'Ads & Monetization',
    code: 'ADS',
    leaderId: 'm-bao-lead',
    leaderName: 'Pham Quoc Bao',
    description: 'Real-time bidding engines, campaign pacing algorithms, and analytics ingestion.',
    status: 'ACTIVE',
    activeTemplateId: 'tpl-ads-v1',
    createdAt: '2025-02-10',
  },
  {
    id: 'team-rnd',
    departmentId: 'dept-backend',
    name: 'R&D & Architecture',
    code: 'RND',
    leaderId: 'm-thang-lead',
    leaderName: 'Vu Duc Thang',
    description: 'Distributed consensus exploration, performance benchmarking, and AI toolchain integrations.',
    status: 'ACTIVE',
    activeTemplateId: 'tpl-rnd-v1',
    createdAt: '2025-03-01',
  },
  {
    id: 'team-db',
    departmentId: 'dept-backend',
    name: 'Database & Reliability (SRE)',
    code: 'DB',
    leaderId: 'm-tri-lead',
    leaderName: 'Doan Minh Tri',
    description: 'Spanner/Postgres cluster tuning, automated failovers, backup verification, and telemetry.',
    status: 'ACTIVE',
    activeTemplateId: 'tpl-db-v1',
    createdAt: '2025-03-15',
  },
];

export const SEED_MEMBERS: Member[] = [
  // Leaders
  {
    id: 'm-head-tuan',
    employeeId: 'EMP-001',
    name: 'Dr. Tuan Nguyen',
    email: 'tuan.nguyen@enterprise.vn',
    title: 'Head of Backend Engineering',
    level: 'Director',
    currentTeamId: 'team-api',
    jiraAccountId: 'jira-tuan-head',
    jiraUsername: 'tuan.head',
    status: 'ACTIVE',
    joinedDate: '2023-01-01',
  },
  {
    id: 'm-minh-lead',
    employeeId: 'EMP-002',
    name: 'Nguyen Van Minh',
    email: 'minh.nguyen@enterprise.vn',
    title: 'API Team Lead',
    level: 'Staff Engineer',
    currentTeamId: 'team-api',
    jiraAccountId: 'jira-minh-lead',
    jiraUsername: 'minh.nv',
    status: 'ACTIVE',
    joinedDate: '2023-04-15',
  },
  {
    id: 'm-mai-lead',
    employeeId: 'EMP-003',
    name: 'Tran Thi Mai',
    email: 'mai.tran@enterprise.vn',
    title: 'Payment Team Lead',
    level: 'Principal Engineer',
    currentTeamId: 'team-payment',
    jiraAccountId: 'jira-mai-lead',
    jiraUsername: 'mai.tt',
    status: 'ACTIVE',
    joinedDate: '2023-05-10',
  },
  {
    id: 'm-long-lead',
    employeeId: 'EMP-004',
    name: 'Le Hoang Long',
    email: 'long.le@enterprise.vn',
    title: 'CMS Team Lead',
    level: 'Senior Tech Lead',
    currentTeamId: 'team-cms',
    jiraAccountId: 'jira-long-lead',
    jiraUsername: 'long.lh',
    status: 'ACTIVE',
    joinedDate: '2023-06-01',
  },
  {
    id: 'm-bao-lead',
    employeeId: 'EMP-005',
    name: 'Pham Quoc Bao',
    email: 'bao.pham@enterprise.vn',
    title: 'Ads Team Lead',
    level: 'Senior Staff Engineer',
    currentTeamId: 'team-ads',
    jiraAccountId: 'jira-bao-lead',
    jiraUsername: 'bao.pq',
    status: 'ACTIVE',
    joinedDate: '2023-07-20',
  },
  {
    id: 'm-thang-lead',
    employeeId: 'EMP-006',
    name: 'Vu Duc Thang',
    email: 'thang.vu@enterprise.vn',
    title: 'R&D Principal Lead',
    level: 'Principal Architect',
    currentTeamId: 'team-rnd',
    jiraAccountId: 'jira-thang-lead',
    jiraUsername: 'thang.vd',
    status: 'ACTIVE',
    joinedDate: '2023-08-01',
  },
  {
    id: 'm-tri-lead',
    employeeId: 'EMP-007',
    name: 'Doan Minh Tri',
    email: 'tri.doan@enterprise.vn',
    title: 'DB & Reliability Lead',
    level: 'Senior SRE Lead',
    currentTeamId: 'team-db',
    jiraAccountId: 'jira-tri-lead',
    jiraUsername: 'tri.dm',
    status: 'ACTIVE',
    joinedDate: '2023-09-10',
  },

  // API Team Members
  {
    id: 'm-tuan',
    employeeId: 'EMP-010',
    name: 'Pham Minh Tuan',
    email: 'tuan.pham@enterprise.vn',
    title: 'Senior Backend Engineer',
    level: 'Senior Engineer',
    currentTeamId: 'team-payment', // Transferred in Sep 2026!
    jiraAccountId: 'jira-tuan-pham',
    jiraUsername: 'tuan.pm',
    status: 'ACTIVE',
    joinedDate: '2024-01-10',
  },
  {
    id: 'm-anh',
    employeeId: 'EMP-011',
    name: 'Nguyen Bao Anh',
    email: 'anh.nguyen@enterprise.vn',
    title: 'Backend Software Engineer',
    level: 'Middle Engineer',
    currentTeamId: 'team-api',
    jiraAccountId: 'jira-anh-nguyen',
    jiraUsername: 'anh.nb',
    status: 'ACTIVE',
    joinedDate: '2024-02-15',
  },
  {
    id: 'm-lam',
    employeeId: 'EMP-012',
    name: 'Dang Van Lam',
    email: 'lam.dang@enterprise.vn',
    title: 'Senior Distributed Systems Engineer',
    level: 'Senior Engineer',
    currentTeamId: 'team-api',
    jiraAccountId: 'jira-lam-dang',
    jiraUsername: 'lam.dv',
    status: 'ACTIVE',
    joinedDate: '2024-03-01',
  },
  {
    id: 'm-nam',
    employeeId: 'EMP-013',
    name: 'Hoang Duc Nam',
    email: 'nam.hoang@enterprise.vn',
    title: 'Backend Engineer (Integrations)',
    level: 'Junior-Middle',
    currentTeamId: 'team-api',
    jiraAccountId: 'jira-nam-hoang',
    jiraUsername: 'nam.hd',
    status: 'ACTIVE',
    joinedDate: '2024-04-10',
  },
  {
    id: 'm-huong',
    employeeId: 'EMP-014',
    name: 'Nguyen Thi Huong',
    email: 'huong.nguyen@enterprise.vn',
    title: 'Backend API Specialist',
    level: 'Middle Engineer',
    currentTeamId: 'team-api',
    jiraAccountId: 'jira-huong-nguyen',
    jiraUsername: 'huong.nt',
    status: 'ACTIVE',
    joinedDate: '2024-05-01',
  },

  // Payment Team Members
  {
    id: 'm-dung',
    employeeId: 'EMP-020',
    name: 'Bui Tien Dung',
    email: 'dung.bui@enterprise.vn',
    title: 'Senior Settlement Engineer',
    level: 'Senior Engineer',
    currentTeamId: 'team-payment',
    jiraAccountId: 'jira-dung-bui',
    jiraUsername: 'dung.bt',
    status: 'ACTIVE',
    joinedDate: '2024-01-20',
  },
  {
    id: 'm-quyen',
    employeeId: 'EMP-021',
    name: 'Vo Thi Quyen',
    email: 'quyen.vo@enterprise.vn',
    title: 'Payment Gateway Engineer',
    level: 'Middle Engineer',
    currentTeamId: 'team-payment',
    jiraAccountId: 'jira-quyen-vo',
    jiraUsername: 'quyen.vt',
    status: 'ACTIVE',
    joinedDate: '2024-03-12',
  },
  {
    id: 'm-hai',
    employeeId: 'EMP-022',
    name: 'Tran Thanh Hai',
    email: 'hai.tran@enterprise.vn',
    title: 'Fraud Detection Backend Engineer',
    level: 'Senior Engineer',
    currentTeamId: 'team-payment',
    jiraAccountId: 'jira-hai-tran',
    jiraUsername: 'hai.tt',
    status: 'ACTIVE',
    joinedDate: '2024-04-05',
  },

  // CMS Team Members
  {
    id: 'm-khanh',
    employeeId: 'EMP-030',
    name: 'Ngo Quoc Khanh',
    email: 'khanh.ngo@enterprise.vn',
    title: 'GraphQL Content Architect',
    level: 'Senior Engineer',
    currentTeamId: 'team-cms',
    jiraAccountId: 'jira-khanh-ngo',
    jiraUsername: 'khanh.nq',
    status: 'ACTIVE',
    joinedDate: '2024-02-01',
  },
  {
    id: 'm-linh',
    employeeId: 'EMP-031',
    name: 'Pham Khanh Linh',
    email: 'linh.pham@enterprise.vn',
    title: 'Media Pipeline Engineer',
    level: 'Middle Engineer',
    currentTeamId: 'team-cms',
    jiraAccountId: 'jira-linh-pham',
    jiraUsername: 'linh.pk',
    status: 'ACTIVE',
    joinedDate: '2024-04-20',
  },
  {
    id: 'm-hoa',
    employeeId: 'EMP-032',
    name: 'Vu Thi Hoa',
    email: 'hoa.vu@enterprise.vn',
    title: 'Editorial APIs Engineer',
    level: 'Junior-Middle',
    currentTeamId: 'team-cms',
    jiraAccountId: 'jira-hoa-vu',
    jiraUsername: 'hoa.vt',
    status: 'ACTIVE',
    joinedDate: '2024-05-15',
  },

  // Ads Team Members
  {
    id: 'm-son',
    employeeId: 'EMP-040',
    name: 'Trinh Hoang Son',
    email: 'son.trinh@enterprise.vn',
    title: 'DSP Bidding Engine Engineer',
    level: 'Senior Engineer',
    currentTeamId: 'team-ads',
    jiraAccountId: 'jira-son-trinh',
    jiraUsername: 'son.th',
    status: 'ACTIVE',
    joinedDate: '2024-02-10',
  },
  {
    id: 'm-nga',
    employeeId: 'EMP-041',
    name: 'Dinh Phuong Nga',
    email: 'nga.dinh@enterprise.vn',
    title: 'Pacing & Targeting Engineer',
    level: 'Middle Engineer',
    currentTeamId: 'team-ads',
    jiraAccountId: 'jira-nga-dinh',
    jiraUsername: 'nga.dp',
    status: 'ACTIVE',
    joinedDate: '2024-03-25',
  },
  {
    id: 'm-truong',
    employeeId: 'EMP-042',
    name: 'Nguyen Van Truong',
    email: 'truong.nguyen@enterprise.vn',
    title: 'Ad Ingestion Stream Engineer',
    level: 'Senior Engineer',
    currentTeamId: 'team-ads',
    jiraAccountId: 'jira-truong-nguyen',
    jiraUsername: 'truong.nv',
    status: 'ACTIVE',
    joinedDate: '2024-06-01',
  },

  // R&D Team Members
  {
    id: 'm-phuc',
    employeeId: 'EMP-050',
    name: 'Hoang Gia Phuc',
    email: 'phuc.hoang@enterprise.vn',
    title: 'R&D Systems Researcher',
    level: 'Staff Architect',
    currentTeamId: 'team-rnd',
    jiraAccountId: 'jira-phuc-hoang',
    jiraUsername: 'phuc.hg',
    status: 'ACTIVE',
    joinedDate: '2024-01-05',
  },
  {
    id: 'm-thao',
    employeeId: 'EMP-051',
    name: 'Do Phuong Thao',
    email: 'thao.do@enterprise.vn',
    title: 'Benchmarking & Rust Core Engineer',
    level: 'Senior Engineer',
    currentTeamId: 'team-rnd',
    jiraAccountId: 'jira-thao-do',
    jiraUsername: 'thao.dp',
    status: 'ACTIVE',
    joinedDate: '2024-04-01',
  },

  // DB Team Members
  {
    id: 'm-hieu',
    employeeId: 'EMP-060',
    name: 'Le Trung Hieu',
    email: 'hieu.le@enterprise.vn',
    title: 'Lead Database Reliability Engineer',
    level: 'Senior SRE',
    currentTeamId: 'team-db',
    jiraAccountId: 'jira-hieu-le',
    jiraUsername: 'hieu.lt',
    status: 'ACTIVE',
    joinedDate: '2024-02-28',
  },
  {
    id: 'm-kien',
    employeeId: 'EMP-061',
    name: 'Bui Dinh Kien',
    email: 'kien.bui@enterprise.vn',
    title: 'Spanner & Storage Engineer',
    level: 'Middle SRE',
    currentTeamId: 'team-db',
    jiraAccountId: 'jira-kien-bui',
    jiraUsername: 'kien.bd',
    status: 'ACTIVE',
    joinedDate: '2024-05-10',
  },
];

// Historical Team Memberships (Models transfer of Pham Minh Tuan from API -> Payment in Sep 2026)
export const SEED_MEMBERSHIPS: TeamMembership[] = [
  // Pham Minh Tuan
  {
    id: 'tms-tuan-jul',
    memberId: 'm-tuan',
    teamId: 'team-api',
    teamName: 'API Core Platform',
    period: '2026-07',
    isPrimary: true,
    roleInTeam: 'MEMBER',
  },
  {
    id: 'tms-tuan-aug',
    memberId: 'm-tuan',
    teamId: 'team-api',
    teamName: 'API Core Platform',
    period: '2026-08',
    isPrimary: true,
    roleInTeam: 'MEMBER',
  },
  {
    id: 'tms-tuan-sep',
    memberId: 'm-tuan',
    teamId: 'team-payment',
    teamName: 'Payment & Billing',
    period: '2026-09',
    isPrimary: true,
    roleInTeam: 'MEMBER',
  },
];

// Seed generic memberships for other members across all periods
const ALL_PERIODS = ['2026-07', '2026-08', '2026-09'];
SEED_MEMBERS.forEach((m) => {
  if (m.id === 'm-tuan') return; // handled explicitly above
  const team = SEED_TEAMS.find((t) => t.id === m.currentTeamId) || SEED_TEAMS[0];
  ALL_PERIODS.forEach((period) => {
    SEED_MEMBERSHIPS.push({
      id: `tms-${m.id}-${period}`,
      memberId: m.id,
      teamId: team.id,
      teamName: team.name,
      period,
      isPrimary: true,
      roleInTeam: m.id.includes('lead') ? 'LEADER' : 'MEMBER',
    });
  });
});

export const SEED_RANK_SCHEME: RankScheme = {
  id: 'rs-standard-2026',
  name: 'Standard Engineering Rank Scheme (2026)',
  code: 'STD_ENG_2026',
  isDefault: true,
  description: 'Enterprise standard 7-tier performance grading and salary coefficient multiplier curve.',
  tiers: [
    { id: 'tier-aplus', rank: 'A+', minScore: 9.8, maxScore: 10.0, coefficient: 1.4, description: 'Exceptional Leadership & Impact', color: 'emerald' },
    { id: 'tier-a', rank: 'A', minScore: 9.4, maxScore: 9.79, coefficient: 1.3, description: 'Exceeds High Expectations', color: 'green' },
    { id: 'tier-bplus', rank: 'B+', minScore: 9.0, maxScore: 9.39, coefficient: 1.2, description: 'Strong & Consistent Performer', color: 'blue' },
    { id: 'tier-b', rank: 'B', minScore: 8.0, maxScore: 8.99, coefficient: 1.1, description: 'Meets Full Standards', color: 'cyan' },
    { id: 'tier-c', rank: 'C', minScore: 7.0, maxScore: 7.99, coefficient: 1.0, description: 'Acceptable Baseline Target', color: 'amber' },
    { id: 'tier-d', rank: 'D', minScore: 6.0, maxScore: 6.99, coefficient: 0.8, description: 'Underperforming / Needs Improvement', color: 'orange' },
    { id: 'tier-e', rank: 'E', minScore: 0.0, maxScore: 5.99, coefficient: 0.6, description: 'Critical Performance Concern', color: 'red' },
  ],
};

export const SEED_KPI_TEMPLATES: KpiTemplate[] = [
  // API Core Platform v1.0 (Used in historical 2026-07)
  {
    id: 'tpl-api-v1',
    code: 'API_KPI_V1',
    name: 'API Platform KPI v1.0 (Historical)',
    departmentId: 'dept-backend',
    teamId: 'team-api',
    version: 'v1.0',
    versionNumber: 1,
    status: 'RETIRED',
    totalScore: 10.0,
    createdBy: 'Nguyen Van Minh',
    createdAt: '2026-01-05',
    updatedAt: '2026-01-10',
    publishedAt: '2026-01-15',
    effectiveFromPeriod: '2026-01',
    effectiveToPeriod: '2026-08',
    changeLog: 'Initial release of API Platform performance criteria.',
    criteria: [
      {
        id: 'crit-api-v1-delivery',
        name: 'Sprint Delivery Velocity & Commitment',
        code: 'DELIVERY',
        description: 'Measures completed story points against sprint commitments.',
        maxScore: 4.0,
        evaluationMethod: 'AUTO',
        evidenceSource: 'JIRA',
        metricConfig: {
          metricId: 'm-task-completion-rate',
          metricKey: 'TASK_COMPLETION_RATE',
          metricName: 'Sprint / Task Completion Rate',
          includedIssueTypes: ['Story', 'Task', 'Improvement'],
          completionStatuses: ['Done', 'Closed'],
          deadlineField: 'duedate',
          periodAttribution: 'RESOLVED_DATE',
          storyPointWeighted: true,
          excludeCancelled: true,
        },
        scoringRule: {
          type: 'THRESHOLD',
          thresholds: [
            { id: 'r1', operator: '>=', value: 95, score: 4.0, label: '>= 95% -> 4.0 pts' },
            { id: 'r2', operator: '>=', value: 90, score: 3.6, label: '90% - 94% -> 3.6 pts' },
            { id: 'r3', operator: '>=', value: 85, score: 3.2, label: '85% - 89% -> 3.2 pts' },
            { id: 'r4', operator: '>=', value: 80, score: 2.6, label: '80% - 84% -> 2.6 pts' },
            { id: 'r5', operator: '<', value: 80, score: 2.0, label: '< 80% -> 2.0 pts' },
          ],
          fallbackScore: 2.0,
        },
        reviewRequired: false,
      },
      {
        id: 'crit-api-v1-quality',
        name: 'Code Quality & Defect Ratio',
        code: 'QUALITY',
        description: 'Measures low post-release bug ratio and clean review practices.',
        maxScore: 3.0,
        evaluationMethod: 'AUTO',
        evidenceSource: 'JIRA',
        metricConfig: {
          metricId: 'm-bug-rate',
          metricKey: 'BUG_RATE',
          metricName: 'Defect & Bug Ratio',
          includedIssueTypes: ['Bug'],
          completionStatuses: ['Done', 'Closed'],
          deadlineField: 'duedate',
          periodAttribution: 'RESOLVED_DATE',
          storyPointWeighted: false,
          excludeCancelled: true,
        },
        scoringRule: {
          type: 'THRESHOLD',
          thresholds: [
            { id: 'q1', operator: '<=', value: 5, score: 3.0, label: '<= 5% Bugs -> 3.0 pts' },
            { id: 'q2', operator: '<=', value: 10, score: 2.6, label: '5.1% - 10% -> 2.6 pts' },
            { id: 'q3', operator: '<=', value: 15, score: 2.2, label: '10.1% - 15% -> 2.2 pts' },
            { id: 'q4', operator: '>', value: 15, score: 1.5, label: '> 15% Bugs -> 1.5 pts' },
          ],
          fallbackScore: 1.5,
        },
        reviewRequired: true,
      },
      {
        id: 'crit-api-v1-incident',
        name: 'Production Incident Mitigation',
        code: 'INCIDENT',
        description: 'Zero high severity P1/P2 incidents generated.',
        maxScore: 2.0,
        evaluationMethod: 'AUTO',
        evidenceSource: 'JIRA',
        metricConfig: {
          metricId: 'm-incident-count',
          metricKey: 'INCIDENT_COUNT',
          metricName: 'P1 / P2 Production Incident Count',
          includedIssueTypes: ['Incident'],
          completionStatuses: ['Done', 'Closed'],
          deadlineField: 'duedate',
          periodAttribution: 'RESOLVED_DATE',
          storyPointWeighted: false,
          excludeCancelled: true,
        },
        scoringRule: {
          type: 'THRESHOLD',
          thresholds: [
            { id: 'i1', operator: '==', value: 0, score: 2.0, label: '0 Incidents -> 2.0 pts' },
            { id: 'i2', operator: '==', value: 1, score: 1.2, label: '1 Incident -> 1.2 pts' },
            { id: 'i3', operator: '>=', value: 2, score: 0.5, label: '>= 2 Incidents -> 0.5 pts' },
          ],
          fallbackScore: 0.5,
        },
        reviewRequired: false,
      },
      {
        id: 'crit-api-v1-doc',
        name: 'Technical Documentation & OpenAPI Spec',
        code: 'DOCUMENTATION',
        description: 'Keeping OpenAPI/Swagger specs updated and architecture documents published.',
        maxScore: 1.0,
        evaluationMethod: 'MANUAL',
        evidenceSource: 'CONFLUENCE_DOCS',
        scoringRule: {
          type: 'THRESHOLD',
          thresholds: [
            { id: 'd1', operator: '>=', value: 1, score: 1.0, label: 'Fully Documented -> 1.0 pt' },
            { id: 'd2', operator: '<', value: 1, score: 0.5, label: 'Partial Docs -> 0.5 pt' },
          ],
          fallbackScore: 0.5,
        },
        reviewRequired: true,
      },
    ],
  },

  // API Core Platform v2.0 (Active in 2026-09) - Added On-Time SLA & Reopen Rate!
  {
    id: 'tpl-api-v2',
    code: 'API_KPI_V2',
    name: 'API Platform KPI v2.0 (Active)',
    departmentId: 'dept-backend',
    teamId: 'team-api',
    version: 'v2.0',
    versionNumber: 2,
    status: 'IN_USE',
    totalScore: 10.0,
    createdBy: 'Nguyen Van Minh',
    createdAt: '2026-08-25',
    updatedAt: '2026-08-30',
    publishedAt: '2026-09-01',
    effectiveFromPeriod: '2026-09',
    changeLog: 'Enhanced with On-Time SLA metric, QA Reopen tracking, and adjusted criteria weighting for tighter SLA precision.',
    clonedFromId: 'tpl-api-v1',
    criteria: [
      {
        id: 'crit-api-v2-ontime',
        name: 'On-time Story Delivery Rate',
        code: 'ON_TIME_DELIVERY',
        description: 'Story points completed on or before target deadline dates.',
        maxScore: 3.5,
        evaluationMethod: 'AUTO',
        evidenceSource: 'JIRA',
        metricConfig: {
          metricId: 'm-ontime-rate',
          metricKey: 'ON_TIME_COMPLETION_RATE',
          metricName: 'On-time Completion Rate',
          includedIssueTypes: ['Story', 'Task', 'Improvement'],
          completionStatuses: ['Done', 'Closed'],
          deadlineField: 'duedate',
          periodAttribution: 'RESOLVED_DATE',
          storyPointWeighted: true,
          excludeCancelled: true,
        },
        scoringRule: {
          type: 'THRESHOLD',
          thresholds: [
            { id: 'ot1', operator: '>=', value: 95, score: 3.5, label: '>= 95% On-Time -> 3.5 pts' },
            { id: 'ot2', operator: '>=', value: 90, score: 3.1, label: '90% - 94% -> 3.1 pts' },
            { id: 'ot3', operator: '>=', value: 85, score: 2.7, label: '85% - 89% -> 2.7 pts' },
            { id: 'ot4', operator: '>=', value: 80, score: 2.2, label: '80% - 84% -> 2.2 pts' },
            { id: 'ot5', operator: '<', value: 80, score: 1.5, label: '< 80% -> 1.5 pts' },
          ],
          fallbackScore: 1.5,
        },
        reviewRequired: false,
      },
      {
        id: 'crit-api-v2-quality',
        name: 'Code & QA Reopen Stability',
        code: 'QUALITY_REOPEN',
        description: 'Measures low bug ratio + low QA task reopen events.',
        maxScore: 2.5,
        evaluationMethod: 'AUTO',
        evidenceSource: 'JIRA',
        metricConfig: {
          metricId: 'm-bug-rate',
          metricKey: 'BUG_RATE',
          metricName: 'Defect & Bug Ratio',
          includedIssueTypes: ['Bug'],
          completionStatuses: ['Done', 'Closed'],
          deadlineField: 'duedate',
          periodAttribution: 'RESOLVED_DATE',
          storyPointWeighted: false,
          excludeCancelled: true,
        },
        scoringRule: {
          type: 'THRESHOLD',
          thresholds: [
            { id: 'qr1', operator: '<=', value: 5, score: 2.5, label: '<= 5% Bugs -> 2.5 pts' },
            { id: 'qr2', operator: '<=', value: 10, score: 2.1, label: '5.1% - 10% -> 2.1 pts' },
            { id: 'qr3', operator: '<=', value: 15, score: 1.7, label: '10.1% - 15% -> 1.7 pts' },
            { id: 'qr4', operator: '>', value: 15, score: 1.0, label: '> 15% -> 1.0 pt' },
          ],
          fallbackScore: 1.0,
        },
        reviewRequired: true,
      },
      {
        id: 'crit-api-v2-incident',
        name: 'Production Outage & SLA Defense',
        code: 'INCIDENT_SLA',
        description: 'Zero high severity P1/P2 production incidents.',
        maxScore: 2.0,
        evaluationMethod: 'AUTO',
        evidenceSource: 'JIRA',
        metricConfig: {
          metricId: 'm-incident-count',
          metricKey: 'INCIDENT_COUNT',
          metricName: 'P1 / P2 Production Incident Count',
          includedIssueTypes: ['Incident'],
          completionStatuses: ['Done', 'Closed'],
          deadlineField: 'duedate',
          periodAttribution: 'RESOLVED_DATE',
          storyPointWeighted: false,
          excludeCancelled: true,
        },
        scoringRule: {
          type: 'THRESHOLD',
          thresholds: [
            { id: 'i1', operator: '==', value: 0, score: 2.0, label: '0 Outages -> 2.0 pts' },
            { id: 'i2', operator: '==', value: 1, score: 1.2, label: '1 Outage -> 1.2 pts' },
            { id: 'i3', operator: '>=', value: 2, score: 0.4, label: '>= 2 Outages -> 0.4 pts' },
          ],
          fallbackScore: 0.4,
        },
        reviewRequired: false,
      },
      {
        id: 'crit-api-v2-carryover',
        name: 'Low Carry-Over Discipline',
        code: 'CARRYOVER_DISCIPLINE',
        description: 'Sprint planning precision and minimizing carried-over work.',
        maxScore: 1.0,
        evaluationMethod: 'AUTO',
        evidenceSource: 'JIRA',
        metricConfig: {
          metricId: 'm-carryover-rate',
          metricKey: 'CARRY_OVER_RATE',
          metricName: 'Task Carry-over Rate',
          includedIssueTypes: ['Story', 'Task'],
          completionStatuses: ['Done', 'Closed'],
          deadlineField: 'duedate',
          periodAttribution: 'RESOLVED_DATE',
          storyPointWeighted: false,
          excludeCancelled: true,
        },
        scoringRule: {
          type: 'THRESHOLD',
          thresholds: [
            { id: 'co1', operator: '<=', value: 8, score: 1.0, label: '<= 8% Carryover -> 1.0 pt' },
            { id: 'co2', operator: '<=', value: 16, score: 0.7, label: '8.1% - 16% -> 0.7 pt' },
            { id: 'co3', operator: '>', value: 16, score: 0.3, label: '> 16% -> 0.3 pt' },
          ],
          fallbackScore: 0.3,
        },
        reviewRequired: false,
      },
      {
        id: 'crit-api-v2-knowledge',
        name: 'Technical Sharing & RFC Architecture',
        code: 'KNOWLEDGE_SHARING',
        description: 'Technical seminars, mentorship, and RFC architecture contributions.',
        maxScore: 1.0,
        evaluationMethod: 'ASSISTED',
        evidenceSource: 'CONFLUENCE_DOCS',
        metricConfig: {
          metricId: 'm-knowledge-sharing',
          metricKey: 'KNOWLEDGE_SHARING',
          metricName: 'Technical Sharing & RFC Contributions',
          includedIssueTypes: ['Task', 'Support'],
          completionStatuses: ['Done', 'Closed'],
          deadlineField: 'duedate',
          periodAttribution: 'RESOLVED_DATE',
          storyPointWeighted: false,
          excludeCancelled: true,
        },
        scoringRule: {
          type: 'THRESHOLD',
          thresholds: [
            { id: 'ks1', operator: '>=', value: 2, score: 1.0, label: '>= 2 Sessions -> 1.0 pt' },
            { id: 'ks2', operator: '>=', value: 1, score: 0.8, label: '1 Session -> 0.8 pt' },
            { id: 'ks3', operator: '<', value: 1, score: 0.4, label: '0 Sessions -> 0.4 pt' },
          ],
          fallbackScore: 0.4,
        },
        reviewRequired: true,
      },
    ],
  },

  // Payment & Billing Template v1.0
  {
    id: 'tpl-pay-v1',
    code: 'PAY_KPI_V1',
    name: 'Payment & Billing KPI v1.0',
    departmentId: 'dept-backend',
    teamId: 'team-payment',
    version: 'v1.0',
    versionNumber: 1,
    status: 'IN_USE',
    totalScore: 10.0,
    createdBy: 'Tran Thi Mai',
    createdAt: '2026-02-15',
    updatedAt: '2026-02-20',
    publishedAt: '2026-03-01',
    effectiveFromPeriod: '2026-03',
    criteria: [
      {
        id: 'crit-pay-settlement',
        name: 'Payment Reconciliation & Settlement SLA',
        code: 'SETTLEMENT_SLA',
        description: 'Zero financial discrepancy and on-time settlement batch jobs.',
        maxScore: 4.0,
        evaluationMethod: 'AUTO',
        evidenceSource: 'JIRA',
        metricConfig: {
          metricId: 'm-ontime-rate',
          metricKey: 'ON_TIME_COMPLETION_RATE',
          metricName: 'On-time Completion Rate',
          includedIssueTypes: ['Story', 'Task'],
          completionStatuses: ['Done'],
          deadlineField: 'duedate',
          periodAttribution: 'RESOLVED_DATE',
          storyPointWeighted: true,
          excludeCancelled: true,
        },
        scoringRule: {
          type: 'THRESHOLD',
          thresholds: [
            { id: 'p1', operator: '>=', value: 95, score: 4.0, label: '>= 95% -> 4.0 pts' },
            { id: 'p2', operator: '>=', value: 90, score: 3.5, label: '90% - 94% -> 3.5 pts' },
            { id: 'p3', operator: '<', value: 90, score: 2.5, label: '< 90% -> 2.5 pts' },
          ],
          fallbackScore: 2.5,
        },
        reviewRequired: false,
      },
      {
        id: 'crit-pay-security',
        name: 'PCI-DSS & Security Compliance',
        code: 'SECURITY_COMPLIANCE',
        description: 'Zero critical vulnerability in payment endpoints and audit compliance.',
        maxScore: 3.0,
        evaluationMethod: 'AUTO',
        evidenceSource: 'JIRA',
        metricConfig: {
          metricId: 'm-bug-rate',
          metricKey: 'BUG_RATE',
          metricName: 'Defect & Bug Ratio',
          includedIssueTypes: ['Bug'],
          completionStatuses: ['Done'],
          deadlineField: 'duedate',
          periodAttribution: 'RESOLVED_DATE',
          storyPointWeighted: false,
          excludeCancelled: true,
        },
        scoringRule: {
          type: 'THRESHOLD',
          thresholds: [
            { id: 'ps1', operator: '<=', value: 3, score: 3.0, label: '<= 3% Defects -> 3.0 pts' },
            { id: 'ps2', operator: '<=', value: 8, score: 2.4, label: '3.1% - 8% -> 2.4 pts' },
            { id: 'ps3', operator: '>', value: 8, score: 1.5, label: '> 8% -> 1.5 pts' },
          ],
          fallbackScore: 1.5,
        },
        reviewRequired: true,
      },
      {
        id: 'crit-pay-incident',
        name: 'Transaction Outages & Incident Shield',
        code: 'TRANSACTION_INCIDENT',
        description: 'Zero gateway payment drops or checkout outages.',
        maxScore: 2.0,
        evaluationMethod: 'AUTO',
        evidenceSource: 'JIRA',
        metricConfig: {
          metricId: 'm-incident-count',
          metricKey: 'INCIDENT_COUNT',
          metricName: 'P1 / P2 Production Incident Count',
          includedIssueTypes: ['Incident'],
          completionStatuses: ['Done'],
          deadlineField: 'duedate',
          periodAttribution: 'RESOLVED_DATE',
          storyPointWeighted: false,
          excludeCancelled: true,
        },
        scoringRule: {
          type: 'THRESHOLD',
          thresholds: [
            { id: 'pi1', operator: '==', value: 0, score: 2.0, label: '0 Incidents -> 2.0 pts' },
            { id: 'pi2', operator: '>=', value: 1, score: 0.5, label: '>= 1 Incident -> 0.5 pts' },
          ],
          fallbackScore: 0.5,
        },
        reviewRequired: false,
      },
      {
        id: 'crit-pay-knowledge',
        name: 'Partner Integration Runbooks',
        code: 'PARTNER_RUNBOOKS',
        description: 'Documenting banking partner APIs and failover protocols.',
        maxScore: 1.0,
        evaluationMethod: 'MANUAL',
        evidenceSource: 'CONFLUENCE_DOCS',
        scoringRule: {
          type: 'THRESHOLD',
          thresholds: [
            { id: 'pr1', operator: '>=', value: 1, score: 1.0, label: 'Complete Runbooks -> 1.0 pt' },
            { id: 'pr2', operator: '<', value: 1, score: 0.5, label: 'Incomplete -> 0.5 pt' },
          ],
          fallbackScore: 0.5,
        },
        reviewRequired: true,
      },
    ],
  },

  // CMS Template
  {
    id: 'tpl-cms-v1',
    code: 'CMS_KPI_V1',
    name: 'CMS & Content Services KPI v1.0',
    departmentId: 'dept-backend',
    teamId: 'team-cms',
    version: 'v1.0',
    versionNumber: 1,
    status: 'IN_USE',
    totalScore: 10.0,
    createdBy: 'Le Hoang Long',
    createdAt: '2026-02-01',
    updatedAt: '2026-02-10',
    publishedAt: '2026-02-15',
    criteria: [
      {
        id: 'crit-cms-delivery',
        name: 'Feature Delivery Rate',
        code: 'CMS_DELIVERY',
        description: 'On-time delivery of editorial tools.',
        maxScore: 4.0,
        evaluationMethod: 'AUTO',
        evidenceSource: 'JIRA',
        metricConfig: {
          metricId: 'm-ontime-rate',
          metricKey: 'ON_TIME_COMPLETION_RATE',
          metricName: 'On-time Completion Rate',
          includedIssueTypes: ['Story', 'Task'],
          completionStatuses: ['Done'],
          deadlineField: 'duedate',
          periodAttribution: 'RESOLVED_DATE',
          storyPointWeighted: true,
          excludeCancelled: true,
        },
        scoringRule: {
          type: 'THRESHOLD',
          thresholds: [
            { id: 'cd1', operator: '>=', value: 92, score: 4.0, label: '>= 92% -> 4.0 pts' },
            { id: 'cd2', operator: '>=', value: 85, score: 3.4, label: '85% - 91% -> 3.4 pts' },
            { id: 'cd3', operator: '<', value: 85, score: 2.2, label: '< 85% -> 2.2 pts' },
          ],
          fallbackScore: 2.2,
        },
        reviewRequired: false,
      },
      {
        id: 'crit-cms-quality',
        name: 'Media Pipeline Quality',
        code: 'CMS_QUALITY',
        description: 'Low defect rate in image/video transformation.',
        maxScore: 3.0,
        evaluationMethod: 'AUTO',
        evidenceSource: 'JIRA',
        metricConfig: {
          metricId: 'm-bug-rate',
          metricKey: 'BUG_RATE',
          metricName: 'Defect & Bug Ratio',
          includedIssueTypes: ['Bug'],
          completionStatuses: ['Done'],
          deadlineField: 'duedate',
          periodAttribution: 'RESOLVED_DATE',
          storyPointWeighted: false,
          excludeCancelled: true,
        },
        scoringRule: {
          type: 'THRESHOLD',
          thresholds: [
            { id: 'cq1', operator: '<=', value: 6, score: 3.0, label: '<= 6% -> 3.0 pts' },
            { id: 'cq2', operator: '<=', value: 12, score: 2.4, label: '6.1% - 12% -> 2.4 pts' },
            { id: 'cq3', operator: '>', value: 12, score: 1.5, label: '> 12% -> 1.5 pts' },
          ],
          fallbackScore: 1.5,
        },
        reviewRequired: true,
      },
      {
        id: 'crit-cms-incident',
        name: 'GraphQL API Uptime',
        code: 'CMS_UPTIME',
        description: 'Zero editorial API downtime.',
        maxScore: 2.0,
        evaluationMethod: 'AUTO',
        evidenceSource: 'JIRA',
        metricConfig: {
          metricId: 'm-incident-count',
          metricKey: 'INCIDENT_COUNT',
          metricName: 'P1 / P2 Production Incident Count',
          includedIssueTypes: ['Incident'],
          completionStatuses: ['Done'],
          deadlineField: 'duedate',
          periodAttribution: 'RESOLVED_DATE',
          storyPointWeighted: false,
          excludeCancelled: true,
        },
        scoringRule: {
          type: 'THRESHOLD',
          thresholds: [
            { id: 'ci1', operator: '==', value: 0, score: 2.0, label: '0 Outages -> 2.0 pts' },
            { id: 'ci2', operator: '>=', value: 1, score: 0.8, label: '>= 1 Outage -> 0.8 pt' },
          ],
          fallbackScore: 0.8,
        },
        reviewRequired: false,
      },
      {
        id: 'crit-cms-support',
        name: 'Editorial Team Support Satisfaction',
        code: 'CMS_SUPPORT',
        description: 'Support turn-around time for newsroom editors.',
        maxScore: 1.0,
        evaluationMethod: 'MANUAL',
        evidenceSource: 'MANUAL_EVIDENCE',
        scoringRule: {
          type: 'THRESHOLD',
          thresholds: [
            { id: 'cs1', operator: '>=', value: 1, score: 1.0, label: 'High Satisfaction -> 1.0 pt' },
            { id: 'cs2', operator: '<', value: 1, score: 0.5, label: 'Standard -> 0.5 pt' },
          ],
          fallbackScore: 0.5,
        },
        reviewRequired: true,
      },
    ],
  },

  // Ads Template
  {
    id: 'tpl-ads-v1',
    code: 'ADS_KPI_V1',
    name: 'Ads & Monetization KPI v1.0',
    departmentId: 'dept-backend',
    teamId: 'team-ads',
    version: 'v1.0',
    versionNumber: 1,
    status: 'IN_USE',
    totalScore: 10.0,
    createdBy: 'Pham Quoc Bao',
    createdAt: '2026-02-15',
    updatedAt: '2026-02-25',
    publishedAt: '2026-03-01',
    criteria: [
      {
        id: 'crit-ads-latency',
        name: 'Bidding Engine Sub-20ms SLA & Delivery',
        code: 'ADS_SLA',
        description: 'Delivering low latency real-time bid features.',
        maxScore: 4.5,
        evaluationMethod: 'AUTO',
        evidenceSource: 'JIRA',
        metricConfig: {
          metricId: 'm-ontime-rate',
          metricKey: 'ON_TIME_COMPLETION_RATE',
          metricName: 'On-time Completion Rate',
          includedIssueTypes: ['Story', 'Task'],
          completionStatuses: ['Done'],
          deadlineField: 'duedate',
          periodAttribution: 'RESOLVED_DATE',
          storyPointWeighted: true,
          excludeCancelled: true,
        },
        scoringRule: {
          type: 'THRESHOLD',
          thresholds: [
            { id: 'as1', operator: '>=', value: 95, score: 4.5, label: '>= 95% -> 4.5 pts' },
            { id: 'as2', operator: '>=', value: 88, score: 3.8, label: '88% - 94% -> 3.8 pts' },
            { id: 'as3', operator: '<', value: 88, score: 2.5, label: '< 88% -> 2.5 pts' },
          ],
          fallbackScore: 2.5,
        },
        reviewRequired: false,
      },
      {
        id: 'crit-ads-quality',
        name: 'Revenue Pipeline Defect Ratio',
        code: 'ADS_QUALITY',
        description: 'Zero impression loss due to software bugs.',
        maxScore: 3.5,
        evaluationMethod: 'AUTO',
        evidenceSource: 'JIRA',
        metricConfig: {
          metricId: 'm-bug-rate',
          metricKey: 'BUG_RATE',
          metricName: 'Defect & Bug Ratio',
          includedIssueTypes: ['Bug'],
          completionStatuses: ['Done'],
          deadlineField: 'duedate',
          periodAttribution: 'RESOLVED_DATE',
          storyPointWeighted: false,
          excludeCancelled: true,
        },
        scoringRule: {
          type: 'THRESHOLD',
          thresholds: [
            { id: 'aq1', operator: '<=', value: 5, score: 3.5, label: '<= 5% -> 3.5 pts' },
            { id: 'aq2', operator: '<=', value: 10, score: 2.8, label: '5.1% - 10% -> 2.8 pts' },
            { id: 'aq3', operator: '>', value: 10, score: 1.8, label: '> 10% -> 1.8 pts' },
          ],
          fallbackScore: 1.8,
        },
        reviewRequired: true,
      },
      {
        id: 'crit-ads-incident',
        name: 'Bidding System Zero Outages',
        code: 'ADS_INCIDENT',
        description: 'Preventing production ad server timeouts.',
        maxScore: 2.0,
        evaluationMethod: 'AUTO',
        evidenceSource: 'JIRA',
        metricConfig: {
          metricId: 'm-incident-count',
          metricKey: 'INCIDENT_COUNT',
          metricName: 'P1 / P2 Production Incident Count',
          includedIssueTypes: ['Incident'],
          completionStatuses: ['Done'],
          deadlineField: 'duedate',
          periodAttribution: 'RESOLVED_DATE',
          storyPointWeighted: false,
          excludeCancelled: true,
        },
        scoringRule: {
          type: 'THRESHOLD',
          thresholds: [
            { id: 'ai1', operator: '==', value: 0, score: 2.0, label: '0 Incidents -> 2.0 pts' },
            { id: 'ai2', operator: '>=', value: 1, score: 0.5, label: '>= 1 Incident -> 0.5 pts' },
          ],
          fallbackScore: 0.5,
        },
        reviewRequired: false,
      },
    ],
  },

  // R&D & Architecture Template
  {
    id: 'tpl-rnd-v1',
    code: 'RND_KPI_V1',
    name: 'R&D & Architecture KPI v1.0',
    departmentId: 'dept-backend',
    teamId: 'team-rnd',
    version: 'v1.0',
    versionNumber: 1,
    status: 'IN_USE',
    totalScore: 10.0,
    createdBy: 'Vu Duc Thang',
    createdAt: '2026-03-01',
    updatedAt: '2026-03-10',
    publishedAt: '2026-03-15',
    criteria: [
      {
        id: 'crit-rnd-poc',
        name: 'Technical PoC Delivery & Benchmarks',
        code: 'RND_POC',
        description: 'Delivering evaluated prototypes and performance whitepapers.',
        maxScore: 4.0,
        evaluationMethod: 'AUTO',
        evidenceSource: 'JIRA',
        metricConfig: {
          metricId: 'm-task-completion-rate',
          metricKey: 'TASK_COMPLETION_RATE',
          metricName: 'Sprint / Task Completion Rate',
          includedIssueTypes: ['Story', 'Task', 'Improvement'],
          completionStatuses: ['Done'],
          deadlineField: 'duedate',
          periodAttribution: 'RESOLVED_DATE',
          storyPointWeighted: true,
          excludeCancelled: true,
        },
        scoringRule: {
          type: 'THRESHOLD',
          thresholds: [
            { id: 'rd1', operator: '>=', value: 90, score: 4.0, label: '>= 90% -> 4.0 pts' },
            { id: 'rd2', operator: '>=', value: 80, score: 3.2, label: '80% - 89% -> 3.2 pts' },
            { id: 'rd3', operator: '<', value: 80, score: 2.0, label: '< 80% -> 2.0 pts' },
          ],
          fallbackScore: 2.0,
        },
        reviewRequired: false,
      },
      {
        id: 'crit-rnd-rfc',
        name: 'Architecture RFCs & Patents',
        code: 'RND_RFC',
        description: 'Published RFC designs accepted by Backend Architecture Council.',
        maxScore: 3.5,
        evaluationMethod: 'ASSISTED',
        evidenceSource: 'CONFLUENCE_DOCS',
        metricConfig: {
          metricId: 'm-knowledge-sharing',
          metricKey: 'KNOWLEDGE_SHARING',
          metricName: 'Technical Sharing & RFC Contributions',
          includedIssueTypes: ['Task'],
          completionStatuses: ['Done'],
          deadlineField: 'duedate',
          periodAttribution: 'RESOLVED_DATE',
          storyPointWeighted: false,
          excludeCancelled: true,
        },
        scoringRule: {
          type: 'THRESHOLD',
          thresholds: [
            { id: 'rf1', operator: '>=', value: 2, score: 3.5, label: '>= 2 RFCs -> 3.5 pts' },
            { id: 'rf2', operator: '>=', value: 1, score: 2.8, label: '1 RFC -> 2.8 pts' },
            { id: 'rf3', operator: '<', value: 1, score: 1.5, label: '0 RFC -> 1.5 pts' },
          ],
          fallbackScore: 1.5,
        },
        reviewRequired: true,
      },
      {
        id: 'crit-rnd-mentor',
        name: 'Engineering Mentorship & Tech Talks',
        code: 'RND_MENTOR',
        description: 'Conducting department-wide tech workshops.',
        maxScore: 2.5,
        evaluationMethod: 'MANUAL',
        evidenceSource: 'MANUAL_EVIDENCE',
        scoringRule: {
          type: 'THRESHOLD',
          thresholds: [
            { id: 'rm1', operator: '>=', value: 1, score: 2.5, label: 'Active Mentorship -> 2.5 pts' },
            { id: 'rm2', operator: '<', value: 1, score: 1.5, label: 'Baseline -> 1.5 pts' },
          ],
          fallbackScore: 1.5,
        },
        reviewRequired: true,
      },
    ],
  },

  // DB & Reliability Template
  {
    id: 'tpl-db-v1',
    code: 'DB_KPI_V1',
    name: 'Database & Reliability (SRE) KPI v1.0',
    departmentId: 'dept-backend',
    teamId: 'team-db',
    version: 'v1.0',
    versionNumber: 1,
    status: 'IN_USE',
    totalScore: 10.0,
    createdBy: 'Doan Minh Tri',
    createdAt: '2026-03-10',
    updatedAt: '2026-03-20',
    publishedAt: '2026-03-25',
    criteria: [
      {
        id: 'crit-db-cluster',
        name: 'Database 99.99% Availability & Cluster Health',
        code: 'DB_AVAILABILITY',
        description: 'Zero unplanned database downtime or data loss.',
        maxScore: 4.5,
        evaluationMethod: 'AUTO',
        evidenceSource: 'JIRA',
        metricConfig: {
          metricId: 'm-incident-count',
          metricKey: 'INCIDENT_COUNT',
          metricName: 'P1 / P2 Production Incident Count',
          includedIssueTypes: ['Incident'],
          completionStatuses: ['Done'],
          deadlineField: 'duedate',
          periodAttribution: 'RESOLVED_DATE',
          storyPointWeighted: false,
          excludeCancelled: true,
        },
        scoringRule: {
          type: 'THRESHOLD',
          thresholds: [
            { id: 'da1', operator: '==', value: 0, score: 4.5, label: '0 Incidents -> 4.5 pts' },
            { id: 'da2', operator: '==', value: 1, score: 2.5, label: '1 Incident -> 2.5 pts' },
            { id: 'da3', operator: '>=', value: 2, score: 1.0, label: '>= 2 Incidents -> 1.0 pt' },
          ],
          fallbackScore: 1.0,
        },
        reviewRequired: false,
      },
      {
        id: 'crit-db-projects',
        name: 'SRE Automation & Failover Drills',
        code: 'DB_AUTOMATION',
        description: 'Automating Spanner/Postgres disaster recovery drills.',
        maxScore: 3.5,
        evaluationMethod: 'AUTO',
        evidenceSource: 'JIRA',
        metricConfig: {
          metricId: 'm-ontime-rate',
          metricKey: 'ON_TIME_COMPLETION_RATE',
          metricName: 'On-time Completion Rate',
          includedIssueTypes: ['Story', 'Task'],
          completionStatuses: ['Done'],
          deadlineField: 'duedate',
          periodAttribution: 'RESOLVED_DATE',
          storyPointWeighted: true,
          excludeCancelled: true,
        },
        scoringRule: {
          type: 'THRESHOLD',
          thresholds: [
            { id: 'do1', operator: '>=', value: 92, score: 3.5, label: '>= 92% -> 3.5 pts' },
            { id: 'do2', operator: '>=', value: 85, score: 2.8, label: '85% - 91% -> 2.8 pts' },
            { id: 'do3', operator: '<', value: 85, score: 1.8, label: '< 85% -> 1.8 pts' },
          ],
          fallbackScore: 1.8,
        },
        reviewRequired: false,
      },
      {
        id: 'crit-db-runbooks',
        name: 'Chaos Engineering & On-Call Playbooks',
        code: 'DB_PLAYBOOKS',
        description: 'Up-to-date runbooks and on-call escalation procedures.',
        maxScore: 2.0,
        evaluationMethod: 'MANUAL',
        evidenceSource: 'CONFLUENCE_DOCS',
        scoringRule: {
          type: 'THRESHOLD',
          thresholds: [
            { id: 'dp1', operator: '>=', value: 1, score: 2.0, label: 'Certified -> 2.0 pts' },
            { id: 'dp2', operator: '<', value: 1, score: 1.0, label: 'Partial -> 1.0 pt' },
          ],
          fallbackScore: 1.0,
        },
        reviewRequired: true,
      },
    ],
  },
];

export const SEED_PERIODS: EvaluationPeriod[] = [
  {
    id: '2026-07',
    code: '2026-07',
    name: 'July 2026',
    startDate: '2026-07-01',
    endDate: '2026-07-31',
    status: 'LOCKED',
    isLocked: true,
    lockedAt: '2026-08-05T14:30:00Z',
    lockedBy: 'Dr. Tuan Nguyen (Department Head)',
    totalMembers: 26,
    systemEvaluatedCount: 26,
    leaderReviewedCount: 26,
    headCalibratedCount: 26,
    finalizedCount: 26,
    lowConfidenceCount: 0,
    dataQualityScore: 98,
  },
  {
    id: '2026-08',
    code: '2026-08',
    name: 'August 2026',
    startDate: '2026-08-01',
    endDate: '2026-08-31',
    status: 'FINALIZED',
    isLocked: false,
    totalMembers: 26,
    systemEvaluatedCount: 26,
    leaderReviewedCount: 26,
    headCalibratedCount: 26,
    finalizedCount: 26,
    lowConfidenceCount: 1,
    dataQualityScore: 95,
  },
  {
    id: '2026-09',
    code: '2026-09',
    name: 'September 2026 (Active)',
    startDate: '2026-09-01',
    endDate: '2026-09-30',
    status: 'LEADER_REVIEW',
    isLocked: false,
    totalMembers: 26,
    systemEvaluatedCount: 26,
    leaderReviewedCount: 19,
    headCalibratedCount: 8,
    finalizedCount: 5,
    lowConfidenceCount: 3,
    dataQualityScore: 91,
  },
];

export const SEED_JIRA_CONFIG: JiraConnectionConfig = {
  workspaceUrl: 'https://enterprise-cloud.atlassian.net',
  status: 'CONNECTED',
  lastSyncTimestamp: '2026-09-15T08:45:12Z',
  syncedIssuesCount: 142,
  mappedMembersCount: 26,
  unmappedMembersCount: 0,
  autoSyncIntervalMinutes: 30,
};

// Generates 140+ realistic Jira tickets across periods with the required scenario artifacts
export function generateSeedJiraIssues(): JiraIssue[] {
  const issues: JiraIssue[] = [];

  // Special scenario ticket for Snapshot vs Current Jira diff demo:
  // API-842: In locked 2026-07 period, snapshot was 5 SP. Current Jira was modified to 8 SP later.
  issues.push({
    key: 'API-842',
    summary: 'Implement OAuth2 PKCE Authorization Code Exchange on Public Gateway',
    assigneeId: 'm-tuan',
    assigneeName: 'Pham Minh Tuan',
    status: 'Done',
    storyPoints: 5, // Snapshot value at lock
    sprint: 'Sprint 2026.07-A',
    issueType: 'Story',
    priority: 'High',
    createdDate: '2026-07-02',
    deadlineDate: '2026-07-15',
    resolvedDate: '2026-07-14',
    isBug: false,
    isIncident: false,
    isSupport: false,
    reopenCount: 0,
    isCarryOver: false,
    periodAttribution: '2026-07',
    attributionReason: 'Resolved in Sprint 2026.07-A before period cutoff.',
    currentJiraStoryPoints: 8, // Current Jira has 8 SP (modified after lock)
    hasDataChangedSinceLock: true,
  });

  // Additional 2026-07 issues
  issues.push(
    {
      key: 'API-843',
      summary: 'Optimize gRPC payload serialization buffer size for payment webhook',
      assigneeId: 'm-tuan',
      assigneeName: 'Pham Minh Tuan',
      status: 'Done',
      storyPoints: 3,
      sprint: 'Sprint 2026.07-A',
      issueType: 'Task',
      priority: 'Medium',
      createdDate: '2026-07-05',
      deadlineDate: '2026-07-18',
      resolvedDate: '2026-07-16',
      isBug: false,
      isIncident: false,
      isSupport: false,
      reopenCount: 0,
      isCarryOver: false,
      periodAttribution: '2026-07',
      attributionReason: 'Resolved on time.',
    },
    {
      key: 'API-844',
      summary: 'Fix race condition during token refresh in high-concurrency Redis cluster',
      assigneeId: 'm-lam',
      assigneeName: 'Dang Van Lam',
      status: 'Done',
      storyPoints: 5,
      sprint: 'Sprint 2026.07-B',
      issueType: 'Bug',
      priority: 'Highest',
      createdDate: '2026-07-12',
      deadlineDate: '2026-07-22',
      resolvedDate: '2026-07-20',
      isBug: true,
      isIncident: false,
      isSupport: false,
      reopenCount: 0,
      isCarryOver: false,
      periodAttribution: '2026-07',
      attributionReason: 'Resolved in Sprint 2026.07-B.',
    }
  );

  // Scenario 2026-08 (Pham Minh Tuan was in API Team)
  issues.push(
    {
      key: 'API-910',
      summary: 'Migrate API Gateway router to Rust-based Envoy filters',
      assigneeId: 'm-tuan',
      assigneeName: 'Pham Minh Tuan',
      status: 'Done',
      storyPoints: 8,
      sprint: 'Sprint 2026.08-A',
      issueType: 'Story',
      priority: 'High',
      createdDate: '2026-08-01',
      deadlineDate: '2026-08-16',
      resolvedDate: '2026-08-15',
      isBug: false,
      isIncident: false,
      isSupport: false,
      reopenCount: 0,
      isCarryOver: false,
      periodAttribution: '2026-08',
      attributionReason: 'Resolved in Sprint 2026.08-A.',
    },
    {
      key: 'API-911',
      summary: 'Implement distributed rate limiter with sliding window counter in Redis',
      assigneeId: 'm-tuan',
      assigneeName: 'Pham Minh Tuan',
      status: 'Done',
      storyPoints: 5,
      sprint: 'Sprint 2026.08-B',
      issueType: 'Task',
      priority: 'Medium',
      createdDate: '2026-08-10',
      deadlineDate: '2026-08-25',
      resolvedDate: '2026-08-24',
      isBug: false,
      isIncident: false,
      isSupport: false,
      reopenCount: 0,
      isCarryOver: false,
      periodAttribution: '2026-08',
      attributionReason: 'Resolved in Sprint 2026.08-B.',
    }
  );

  // Scenario 2026-09 (Pham Minh Tuan TRANSFERRED to Payment Team!)
  issues.push(
    {
      key: 'PAY-401',
      summary: 'Build PCI-DSS Token Vault for Credit Card processing in Payment Switch',
      assigneeId: 'm-tuan',
      assigneeName: 'Pham Minh Tuan',
      status: 'Done',
      storyPoints: 8,
      sprint: 'Sprint 2026.09-A',
      issueType: 'Story',
      priority: 'Highest',
      createdDate: '2026-09-02',
      deadlineDate: '2026-09-18',
      resolvedDate: '2026-09-16',
      isBug: false,
      isIncident: false,
      isSupport: false,
      reopenCount: 0,
      isCarryOver: false,
      periodAttribution: '2026-09',
      attributionReason: 'Resolved in Sprint 2026.09-A after transfer to Payment team.',
    },
    {
      key: 'PAY-402',
      summary: 'Implement automated bank settlement reconciliation batch processor',
      assigneeId: 'm-tuan',
      assigneeName: 'Pham Minh Tuan',
      status: 'Done',
      storyPoints: 5,
      sprint: 'Sprint 2026.09-B',
      issueType: 'Task',
      priority: 'High',
      createdDate: '2026-09-10',
      deadlineDate: '2026-09-26',
      resolvedDate: '2026-09-24',
      isBug: false,
      isIncident: false,
      isSupport: false,
      reopenCount: 0,
      isCarryOver: false,
      periodAttribution: '2026-09',
      attributionReason: 'Resolved in Sprint 2026.09-B.',
    }
  );

  // Scenario: Hoang Duc Nam (m-nam) Missing Deadlines (Low Confidence Case)
  issues.push(
    {
      key: 'API-920',
      summary: 'Upgrade third-party SMS gateway webhook handler',
      assigneeId: 'm-nam',
      assigneeName: 'Hoang Duc Nam',
      status: 'Done',
      storyPoints: 3,
      sprint: 'Sprint 2026.09-A',
      issueType: 'Story',
      priority: 'Medium',
      createdDate: '2026-09-03',
      deadlineDate: null, // Missing Deadline!
      resolvedDate: '2026-09-12',
      isBug: false,
      isIncident: false,
      isSupport: false,
      reopenCount: 0,
      isCarryOver: false,
      periodAttribution: '2026-09',
      attributionReason: 'Resolved in period; target deadline was not set in Jira.',
    },
    {
      key: 'API-921',
      summary: 'Refactor notification email queue consumer',
      assigneeId: 'm-nam',
      assigneeName: 'Hoang Duc Nam',
      status: 'Done',
      storyPoints: 5,
      sprint: 'Sprint 2026.09-A',
      issueType: 'Story',
      priority: 'Medium',
      createdDate: '2026-09-04',
      deadlineDate: null, // Missing Deadline!
      resolvedDate: '2026-09-15',
      isBug: false,
      isIncident: false,
      isSupport: false,
      reopenCount: 0,
      isCarryOver: false,
      periodAttribution: '2026-09',
      attributionReason: 'Resolved in period; target deadline missing.',
    }
  );

  // Scenario: Nguyen Bao Anh (m-anh) Missing Story Points
  issues.push(
    {
      key: 'API-930',
      summary: 'Configure Prometheus histogram buckets for API latency',
      assigneeId: 'm-anh',
      assigneeName: 'Nguyen Bao Anh',
      status: 'Done',
      storyPoints: null, // Missing SP!
      sprint: 'Sprint 2026.09-A',
      issueType: 'Task',
      priority: 'Low',
      createdDate: '2026-09-05',
      deadlineDate: '2026-09-16',
      resolvedDate: '2026-09-14',
      isBug: false,
      isIncident: false,
      isSupport: false,
      reopenCount: 0,
      isCarryOver: false,
      periodAttribution: '2026-09',
      attributionReason: 'Resolved on time; Story Points not estimated.',
    },
    {
      key: 'API-931',
      summary: 'Update API healthcheck endpoint to verify database replica lag',
      assigneeId: 'm-anh',
      assigneeName: 'Nguyen Bao Anh',
      status: 'Done',
      storyPoints: null, // Missing SP!
      sprint: 'Sprint 2026.09-B',
      issueType: 'Task',
      priority: 'Medium',
      createdDate: '2026-09-10',
      deadlineDate: '2026-09-22',
      resolvedDate: '2026-09-20',
      isBug: false,
      isIncident: false,
      isSupport: false,
      reopenCount: 0,
      isCarryOver: false,
      periodAttribution: '2026-09',
      attributionReason: 'Resolved on time; Story Points not estimated.',
    }
  );

  // Scenario: Bui Tien Dung (m-dung) High Carry-Over & KPI Drop
  issues.push(
    {
      key: 'PAY-410',
      summary: 'Refactor async settlement ledger queue processor',
      assigneeId: 'm-dung',
      assigneeName: 'Bui Tien Dung',
      status: 'In Progress',
      storyPoints: 8,
      sprint: 'Sprint 2026.09-A',
      issueType: 'Story',
      priority: 'Highest',
      createdDate: '2026-09-01',
      deadlineDate: '2026-09-15',
      resolvedDate: null,
      isBug: false,
      isIncident: false,
      isSupport: false,
      reopenCount: 1,
      isCarryOver: true,
      carryOverFromSprint: 'Sprint 2026.08-B',
      periodAttribution: '2026-09',
      attributionReason: 'Carried over from August sprint due to external banking API delays.',
    },
    {
      key: 'PAY-411',
      summary: 'Fix double deduction bug during payment timeout retries',
      assigneeId: 'm-dung',
      assigneeName: 'Bui Tien Dung',
      status: 'Done',
      storyPoints: 5,
      sprint: 'Sprint 2026.09-A',
      issueType: 'Bug',
      priority: 'Highest',
      createdDate: '2026-09-05',
      deadlineDate: '2026-09-10',
      resolvedDate: '2026-09-14', // LATE!
      isBug: true,
      isIncident: false,
      isSupport: false,
      reopenCount: 2,
      isCarryOver: true,
      periodAttribution: '2026-09',
      attributionReason: 'Resolved past deadline; 2 QA reopens.',
    },
    {
      key: 'PAY-412',
      summary: 'Implement webhook HMAC signature validation for merchant callback',
      assigneeId: 'm-dung',
      assigneeName: 'Bui Tien Dung',
      status: 'In Progress',
      storyPoints: 5,
      sprint: 'Sprint 2026.09-B',
      issueType: 'Story',
      priority: 'High',
      createdDate: '2026-09-15',
      deadlineDate: '2026-09-25',
      resolvedDate: null,
      isBug: false,
      isIncident: false,
      isSupport: false,
      reopenCount: 0,
      isCarryOver: true,
      periodAttribution: '2026-09',
      attributionReason: 'Carried over across sprints.',
    }
  );

  // Scenario: Dang Van Lam (m-lam) High impact & Leader adjustment
  issues.push(
    {
      key: 'API-950',
      summary: 'Emergency Sunday hotfix for gRPC channel memory leak under 150k RPS',
      assigneeId: 'm-lam',
      assigneeName: 'Dang Van Lam',
      status: 'Done',
      storyPoints: 8,
      sprint: 'Sprint 2026.09-A',
      issueType: 'Task',
      priority: 'Highest',
      createdDate: '2026-09-07',
      deadlineDate: '2026-09-08',
      resolvedDate: '2026-09-08',
      isBug: false,
      isIncident: true,
      isSupport: false,
      reopenCount: 0,
      isCarryOver: false,
      periodAttribution: '2026-09',
      attributionReason: 'Emergency resolution on weekend; prevented major outage.',
    },
    {
      key: 'API-951',
      summary: 'Design and deploy zero-downtime distributed locking mechanism for DB failovers',
      assigneeId: 'm-lam',
      assigneeName: 'Dang Van Lam',
      status: 'Done',
      storyPoints: 8,
      sprint: 'Sprint 2026.09-B',
      issueType: 'Story',
      priority: 'High',
      createdDate: '2026-09-10',
      deadlineDate: '2026-09-24',
      resolvedDate: '2026-09-22',
      isBug: false,
      isIncident: false,
      isSupport: false,
      reopenCount: 0,
      isCarryOver: false,
      periodAttribution: '2026-09',
      attributionReason: 'Delivered ahead of schedule.',
    }
  );

  // Generate synthetic realistic issues for all other members to ensure data richness
  const issueTypes: ('Story' | 'Task' | 'Bug' | 'Incident' | 'Improvement')[] = ['Story', 'Task', 'Improvement', 'Bug', 'Task', 'Story'];
  const titles = [
    'Refactor connection pool timeout handling',
    'Add OpenTelemetry distributed tracing spans',
    'Migrate legacy MySQL query to Spanner distributed index',
    'Optimize Redis LRU cache eviction policy',
    'Implement idempotency key filter for HTTP POST endpoints',
    'Build automated integration test suite for checkout pipeline',
    'Fix memory leak in JSON streaming parser',
    'Upgrade Kubernetes ingress controller SSL certificates',
    'Conduct load testing with k6 up to 50k concurrent users',
    'Publish OpenAPI 3.1 documentation for external partners',
  ];

  let issueCounter = 1000;
  SEED_MEMBERS.forEach((m) => {
    // Skip members who have custom curated scenarios
    if (['m-tuan', 'm-nam', 'm-anh', 'm-dung', 'm-lam'].includes(m.id)) return;

    ALL_PERIODS.forEach((period) => {
      const monthPrefix = period.split('-')[1];
      const count = 3 + Math.floor(Math.random() * 3); // 3 to 5 tickets per period

      for (let i = 0; i < count; i++) {
        issueCounter++;
        const isBug = i === 2 && Math.random() > 0.6;
        const isIncident = i === 3 && Math.random() > 0.85;
        const sp = [2, 3, 5, 8][Math.floor(Math.random() * 4)];
        const day = 5 + i * 5;
        const isLate = Math.random() > 0.8;
        const deadline = `2026-${monthPrefix}-${day < 10 ? '0' + day : day}`;
        const resolved = `2026-${monthPrefix}-${(day + (isLate ? 3 : -1)) < 10 ? '0' + (day + (isLate ? 3 : -1)) : (day + (isLate ? 3 : -1))}`;

        issues.push({
          key: `BED-${issueCounter}`,
          summary: titles[i % titles.length] + ` [${m.name.split(' ').pop()}]`,
          assigneeId: m.id,
          assigneeName: m.name,
          status: 'Done',
          storyPoints: sp,
          sprint: `Sprint 2026.${monthPrefix}-${i % 2 === 0 ? 'A' : 'B'}`,
          issueType: isIncident ? 'Incident' : isBug ? 'Bug' : issueTypes[i % issueTypes.length],
          priority: isIncident ? 'Highest' : isBug ? 'High' : 'Medium',
          createdDate: `2026-${monthPrefix}-01`,
          deadlineDate: deadline,
          resolvedDate: resolved,
          isBug,
          isIncident,
          isSupport: false,
          reopenCount: isBug ? 1 : 0,
          isCarryOver: false,
          periodAttribution: period,
          attributionReason: `Resolved in period ${period}.`,
        });
      }
    });
  });

  return issues;
}

export const SEED_DATA_QUALITY_ISSUES: DataQualityIssue[] = [
  {
    id: 'dq-1',
    memberId: 'm-nam',
    memberName: 'Hoang Duc Nam',
    teamName: 'API Core Platform',
    issueKey: 'API-920',
    issueType: 'MISSING_DEADLINE',
    description: 'Ticket API-920 completed without target deadline field in Jira.',
    affectedMetric: 'On-time Completion Rate',
    affectedCriterion: 'On-time Story Delivery Rate',
    severity: 'WARNING',
    suggestedAction: 'Prompt engineer or Scrum Master to populate Target Due Date.',
    resolved: false,
  },
  {
    id: 'dq-2',
    memberId: 'm-anh',
    memberName: 'Nguyen Bao Anh',
    teamName: 'API Core Platform',
    issueKey: 'API-930',
    issueType: 'MISSING_SP',
    description: 'Ticket API-930 delivered with null Story Points estimation.',
    affectedMetric: 'Sprint / Task Completion Rate',
    affectedCriterion: 'Sprint Delivery Velocity',
    severity: 'WARNING',
    suggestedAction: 'Assign team median story points (3 SP) and mark Medium confidence.',
    resolved: false,
  },
  {
    id: 'dq-3',
    memberId: 'm-tuan',
    memberName: 'Pham Minh Tuan',
    teamName: 'API Core Platform',
    issueKey: 'API-842',
    issueType: 'DATA_MUTATED_AFTER_LOCK',
    description: 'Jira Story Points modified from 5 SP to 8 SP after 2026-07 period was locked.',
    affectedMetric: 'Completed Story Points',
    affectedCriterion: 'Sprint Delivery Velocity & Commitment',
    severity: 'INFO',
    suggestedAction: 'Historical locked snapshot is immutable. Showing current diff in audit log.',
    resolved: true,
  },
];

export const SEED_AUDIT_LOG: AuditEvent[] = [
  {
    id: 'aud-101',
    timestamp: '2026-09-15T09:12:45Z',
    actor: 'Dr. Tuan Nguyen',
    actorRole: 'HEAD',
    action: 'HEAD_CALIBRATED_SCORE',
    entityType: 'EVALUATION',
    entityId: 'eval-m-huong-2026-09',
    entityName: 'Nguyen Thi Huong (2026-09)',
    beforeValue: 'Leader Score: 9.20 (Rank A)',
    afterValue: 'Head Calibrated: 8.70 (Rank B)',
    reason: 'Department rating calibration to normalize baseline distribution across microservices.',
  },
  {
    id: 'aud-102',
    timestamp: '2026-09-14T16:30:10Z',
    actor: 'Nguyen Van Minh',
    actorRole: 'LEADER',
    action: 'LEADER_ADJUSTED_SCORE',
    entityType: 'EVALUATION',
    entityId: 'eval-m-lam-2026-09',
    entityName: 'Dang Van Lam (2026-09)',
    beforeValue: 'System Score: 7.80',
    afterValue: 'Leader Adjusted: 8.60',
    reason: 'Recognized emergency weekend mitigation of P1 gRPC channel leak under 150k RPS load.',
  },
  {
    id: 'aud-103',
    timestamp: '2026-09-01T00:00:01Z',
    actor: 'System Automation',
    actorRole: 'ADMIN',
    action: 'MEMBER_MOVED',
    entityType: 'MEMBER',
    entityId: 'm-tuan',
    entityName: 'Pham Minh Tuan',
    beforeValue: 'Primary Team: API Core Platform',
    afterValue: 'Primary Team: Payment & Billing',
    reason: 'Strategic reassignment for Payment Vault PCI-DSS initiative.',
  },
  {
    id: 'aud-104',
    timestamp: '2026-08-30T10:00:00Z',
    actor: 'Nguyen Van Minh',
    actorRole: 'LEADER',
    action: 'KPI_PUBLISHED',
    entityType: 'KPI_TEMPLATE',
    entityId: 'tpl-api-v2',
    entityName: 'API Platform KPI v2.0',
    beforeValue: 'Status: DRAFT',
    afterValue: 'Status: PUBLISHED (In Use in 2026-09)',
    reason: 'Approved by Head of Backend Engineering for Q3 SLA enforcement.',
  },
  {
    id: 'aud-105',
    timestamp: '2026-08-05T14:30:00Z',
    actor: 'Dr. Tuan Nguyen',
    actorRole: 'HEAD',
    action: 'PERIOD_LOCKED',
    entityType: 'PERIOD',
    entityId: '2026-07',
    entityName: 'Evaluation Period July 2026',
    beforeValue: 'Status: FINALIZED',
    afterValue: 'Status: LOCKED',
    reason: 'Period permanently locked for payroll calculation. Immutable historical snapshot.',
  },
];
